export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST';
export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST';
export const RECEIVE_ARTICLE_LIST = 'RECEIVE_ARTICLE_LIST';

export const REQUEST_ACTIVITY_LIST = 'REQUEST_ACTIVITY_LIST';
export const FETCH_ACTIVITY_LIST = 'FETCH_ACTIVITY_LIST';
export const RECEIVE_ACTIVITY_LIST = 'RECEIVE_ACTIVITY_LIST';

export const REQUEST_MY_ACTIVITY_LIST = 'REQUEST_MY_ACTIVITY_LIST';
export const FETCH_MY_ACTIVITY_LIST = 'FETCH_MY_ACTIVITY_LIST';
export const RECEIVE_MY_ACTIVITY_LIST = 'RECEIVE_MY_ACTIVITY_LIST';

export const REQUEST_ARTICLE_BANNER_LIST = 'REQUEST_ARTICLE_BANNER_LIST';
export const FETCH_ARTICLE_BANNER_LIST = 'FETCH_ARTICLE_BANNER_LIST';
export const RECEIVE_ARTICLE_BANNER_LIST = 'RECEIVE_ARTICLE_BANNER_LIST';
export const REQUEST_TYPE_LIST = 'REQUEST_TYPE_LIST';
export const FETCH_TYPE_LIST = 'FETCH_TYPE_LIST';
export const RECEIVE_TYPE_LIST = 'RECEIVE_TYPE_LIST';

export const REQUEST_GET_PHONE_CODE = 'REQUEST_GET_PHONE_CODE';
export const FETCH_GET_PHONE_CODE = 'FETCH_GET_PHONE_CODE';
export const RECEIVE_GET_PHONE_CODE = 'RECEIVE_GET_PHONE_CODE';
export const FETCH_VALID_PHONE_CODE = 'FETCH_VALID_PHONE_CODE';
export const REQUEST_VALID_PHONE_CODE = 'REQUEST_VALID_PHONE_CODE';
export const RECEIVE_VALID_PHONE_CODE = 'RECEIVE_VALID_PHONE_CODE';

export const REQUEST_LIKE = 'REQUEST_LIKE';
export const FETCH_LIKE = 'FETCH_LIKE';
export const RECEIVE_LIKE = 'RECEIVE_LIKE';
export const REQUEST_UPDATE_LIKE = 'REQUEST_UPDATE_LIKE';
export const FETCH_UPDATE_LIKE = 'FETCH_UPDATE_LIKE';
export const RECEIVE_UPDATE_LIKE = 'RECEIVE_UPDATE_LIKE';


export const REQUEST_ACTIVITY_LIKE = 'REQUEST_ACTIVITY_LIKE';
export const RECEIVE_ACTIVITY_LIKE = 'RECEIVE_ACTIVITY_LIKE';
export const REQUEST_UPDATE_ACTIVITY_LIKE = 'REQUEST_UPDATE_ACTIVITY_LIKE';
export const RECEIVE_UPDATE_ACTIVITY_LIKE = 'RECEIVE_UPDATE_ACTIVITY_LIKE';


export const REQUEST_UPDATE_SHARE = 'REQUEST_UPDATE_SHARE';
export const RECEIVE_UPDATE_SHARE = 'REQUEST_UPDATE_SHARE';
export const REQUEST_UPDATE_ACTIVITY_SHARE = 'REQUEST_UPDATE_ACTIVITY_SHARE';
export const RECEIVE_UPDATE_ACTIVITY_SHARE = 'RECEIVE_UPDATE_ACTIVITY_SHARE';

export const REQUEST_INFO_LIST = 'REQUEST_INFO_LIST';
export const FETCH_INFO_LIST = 'FETCH_INFO_LIST';
export const RECEIVE_INFO_LIST = 'RECEIVE_INFO_LIST';

export const REQUEST_INFO_ACTIVITY_LIST = 'REQUEST_INFO_ACTIVITY_LIST';
export const FETCH_INFO_ACTIVITY_LIST = 'FETCH_INFO_ACTIVITY_LIST';
export const RECEIVE_INFO_ACTIVITY_LIST = 'RECEIVE_INFO_ACTIVITY_LIST';

export const STARTUP = 'STARTUP';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';





